version: '3.8'
services:
  app:
    image: users-api
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '3.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    environment:
      - JWT_SECRET=secret
      - JWT_EXPIRATION=2h
      - PORT=3000
      - DATABASE_IP=192.168.0.18
      - DATABASE_SCHEMA=UsersAPI
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=SenhaBraba123
      - DATABASE_TYPE=postgres
    ports:
      - 3500:3000
